{% set name = "asyncstdlib" %}
{% set version = "3.12.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/asyncstdlib-{{ version }}.tar.gz
  sha256: 2acd0c04e205965cc2bb063b75370df92d207a3035bc4f83fb6b5686cffad7a0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - flit-core
    - pip
    - python >=3.8
  run:
    - python >=3.8

test:
  imports:
    - asyncstdlib
  requires:
    - pip
    - pytest
  source_files:
    - unittests
  commands:
    - pip check
    - pytest unittests

about:
  home: https://github.com/maxfischer2781/asyncstdlib
  summary: The missing async toolbox
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maxfischer2781
