{% set name = "asyncstdlib" %}
{% set version = "3.12.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/asyncstdlib-{{ version }}.tar.gz
  sha256: 83d620553fea73ee924a986e69135bcacb655f6cdc6f2f9e67030a1e259d8be5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - flit-core
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - typing_extensions

test:
  imports:
    - asyncstdlib
  requires:
    - pip
    - pytest
  source_files:
    - unittests
  commands:
    - pip check
    - pytest unittests

about:
  home: https://github.com/maxfischer2781/asyncstdlib
  summary: The missing async toolbox
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maxfischer2781
