{% set name = "asyncstdlib" %}
{% set version = "3.12.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/asyncstdlib-{{ version }}.tar.gz
  sha256: d1f0d439cc9f3ada7c4656590ac145ebeb059b74d9ad1818653a1441b9b873a8

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - flit-core
    - pip
    - python >=3.8
  run:
    - python >=3.8

test:
  imports:
    - asyncstdlib
  requires:
    - pip
    - pytest
  source_files:
    - unittests
  commands:
    - pip check
    - pytest unittests

about:
  home: https://github.com/maxfischer2781/asyncstdlib
  summary: The missing async toolbox
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maxfischer2781
